# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 810dde814752de28e3cb28d0da78e3ab34377db7107ab1d1f7ef2362aec0d3c82b93af4015516da9343b8ba676483eb51276aba84b4095332121bfddb8afe4c8

test:
  secret_key_base: 62fa290687e75f04b5414eb81d24c9c20356ce0852d8b9461bc0e87224328c4841a6238893dbd4bc90cfffb59f022a624a409b0a258c46bbe955e8fbd5cf36e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
